# Generated by Django 5.1 on 2024-10-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunid', models.CharField(max_length=10)),
                ('urunad', models.CharField(max_length=50)),
                ('cinsiyet', models.CharField(choices=[('K', 'Kız'), ('E', 'Erkek')], default='E', max_length=1)),
                ('uruntur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UrunImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='urun_images/')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eweb.urun')),
            ],
        ),
    ]
